[package]
name = "st7701s"
version = "0.1.0"
authors = ["Corey Vixie <corey@vixie.enterprises>"]
edition = "2024"

[dependencies]
log = { version = "0.4" }
linux-embedded-hal = { version = "0.4", default-features = false, features = [
  "spi",
] }
pastey = { version = "0.1" }
spidev = { version = "0.7" }

[[bin]]
name = "st7701s"
path = "src/main.rs"

[lib]
name = "st7701s"
path = "src/lib.rs"
