name: Install Tooling
description: Install any command line utilities or dependencies that will be required for an Ubuntu image to successfully build the driver.

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Move Zig For Great Justice
      uses: mlugg/setup-zig@v2
